### ISSUE TITLE
Connection state

### ISSUE THREAD

**Issue by valsydalv** [matthijs/sqlpp11-connector-postgresql#44]
Hi,
Is it possible to get connection state and reconnect on error?

**Comment by matthijs** [comment]
Hi,

An exception is thrown by the connector library when there is a broken connection or another related error but there is no reconnect policy available. The library does not reconnect when an error occurred.

Regards, Matthijs

**Comment by StiventoUser** [comment]
Ok, I've run into the problem with the PostgreSQL: the PQexec returned null, which caused the exception `throw failure("No result set given");`.
The failure is the base class, so I can't catch it to handle this situation. So, it would be great to know how to reconnect, reconstruct, etc on this error.

Thanks.

**Comment by matthijs** [comment]
The exception class failure inherits sqlpp::exception, so you could catch the exception that way.

According to the documentation you get this error when:
1.) Out of memory condition
2.) Server is not available (when the command can't be sent to the server)

I assume that you got hit by this while the server was not available. In that case I would expect it to throw a broken_connection instead of a failure.

I will look into it and also add a way to check if the connection is healthy.

Regards, Matthijs

**Comment by StiventoUser** [comment]
Cool, thank you.

I mean I can't distinguish this exceptional situation from another, so the broken_connection could solve it.

**Comment by nuertey** [comment]
@matthijs thank you for the library. I second @valsydalv that a means of detecting database disconnection, and how to subsequently reconnect, would be useful. Thank you.
