### ISSUE TITLE
Dynamic loading fails on ArchLinux 2018.4

### ISSUE THREAD

**Issue by sergeken** [matthijs/sqlpp11-connector-postgresql#51]
On ArchLinux cmake creates an invalid compile_commands.json where the variable DSQLPP_DYNAMIC_LOADING_FILENAME is filled with the value of "usr/usr/lib/libpq.so.so".

Changing src/CMakeLists.txt with

```
if (WIN32)
        get_filename_component(POSTGRESQL_LIB_FILE ${PostgreSQL_LIBRARIES} NAME)
elseif(APPLE)
        set(POSTGRESQL_LIB_FILE "lib${PostgreSQL_LIBRARIES}.dylib")
else()
        #set(POSTGRESQL_LIB_FILE "lib${PostgreSQL_LIBRARIES}.so")
        set(POSTGRESQL_LIB_FILE "${PostgreSQL_LIBRARIES}")
endif()
```

Fixes the problem.

**Comment by sjoubert** [comment]
I confirm the issue on Debian testing/buster/10. I get the following error at runtime:
```
sqlpp::exception: Could not load lib: lib/usr/lib/x86_64-1-gnu/libpq.so.so
```
Note that in addition to the prefix and suffix being added to the full path, the path itself is not correct as this library location is `/usr/lib/x86_64-linux-gnu/libpq.so` with `-linux-` instead of `-1-`

Also @sergeken , I'm not sure your fix does the same intended thing (though it seems to be already broken). It seems that the variable is intended to be the filename but the `${PostgreSQL_LIBRARIES}` seems to be a full path. This will work as long as the runtime library is at the same place as the library found during the build.

**Comment by sergeken** [comment]
I agree that the script is populating the full path.  My fix is just removing the bogus "decorations" "usr" and ".so", so that at least the library loads.  It was a quick fix without looking into the problem in depth.

**Comment by sjoubert** [comment]
Note: on my side, the fix from @sergeken does not work (due to `-linux-` being mysteriously replaced by `-1-` as mentioned before).

For now, a working fix for me was simply to comment the same CMake line and let the in-code default (`libpq.so`) do the job.

**Comment by sergeken** [comment]
Just moved back to Fedora, however 28 now, and the fix "still" works.
