### ISSUE TITLE
Returning clause in insert/update statements

### ISSUE THREAD

**Issue by cszawisza** [matthijs/sqlpp11-connector-postgresql#8]
Are there any plans to implement RETURNING clause in driver?

**Comment by matthijs** [comment]
Hi,

From the documentation of PostgreSQL:
This command conforms to the SQL standard, except that the FROM and RETURNING clauses are PostgreSQL extensions, as is the ability to use WITH with UPDATE.

So this will probably not be implemented in the sqlpp11 library.

At this moment the connector returns the affected rows for insert, update and delete queries.

To implement RETURNING in the driver it will probably require some work on the sqlpp11 library too. I will ask @rbock for information and see if we can come up with something clever.

Regards, Matthijs

**Comment by cszawisza** [comment]
I'll be happy to see it works

**Comment by rbock** [comment]
Hi,

In think you should be able to implement RETURNING for postgresql without any changes in sqlpp11.

Take a look at https://github.com/rbock/sqlpp11/blob/master/include/sqlpp11/select.h#L71-L85

It describes all the clauses that are allowed in a SELECT statement. If you have a RETURNING clause, you could create a `select` in the postgresql namespace which allows RETURNING, too.

The RETURNING clause is probably very similar to the select_column_list. It needs to use the is_return_value tag, too. statement_t uses the last return_value_type. Thus, if there is a returning in the statement, it will use that one.

BTW: You could add optional WITH to UPDATE this way, too. WITH is already available, but not in the `sqlpp::update`.

Best,

Roland

**Comment by rbock** [comment]
Since you want to extend insert, the appropriate link would be

https://github.com/rbock/sqlpp11/blob/master/include/sqlpp11/insert.h#L104-L108

But the idea stays the same: You create an insert statement in the postgresql namespace, add a returning clause.

**Comment by cszawisza** [comment]
What is the implementation state?

**Comment by matthijs** [comment]
Roland,

Could you help me out here? I've looked into this but my C++ knowledge in this field is not as good as yours.

As I see it, the query should look as follows:
```c++
const auto &res = db.run(insert_into(tab)
  .set(tab.gamma = true)
  .returning(all_of(tab));
const auto &row = res.front();
std::cout << row.gamma << std::endl;

const auto &res = db.run(insert_into(tab)
  .set(tab.gamma = true)
  .returning(tab.id, tab.gamma));
const auto &row = res.front();
std::cout << "id" << row.id << ", gamma: " << row.gamma << std::endl;
```

The output_expression for the returning keyword is the same as select_column_list as I understand. But I don't see how this is tied together.

So the question is, what code is responsible for getting .set(tab.gamma = true).returning(.. ?

I hope I explained where I get stuck and where I need some help.

I will setup a branch for the returning feature later today.

Regards, Matthijs

**Comment by rbock** [comment]
Hi Matthijs,

The link I posted earlier is the key to defining structure of a statement.

```C++
namespace sqlpp
{
    template<typename Database>
    using blank_insert_t = statement_t<Database,
					insert_t,
					no_into_t, 
					no_insert_value_list_t>;
}
```

You would create something like this:

```C++
namespace sqlpp
{
  namespace postgresql
  {
    template<typename Database>
    using blank_insert_t = statement_t<Database,
					insert_t,
					no_into_t, 
					no_insert_value_list_t,
                                        no_returning_t>;
  }
}
```

Those `insert_t` etc mentioned as template parameters, are structs, which contain templates themselves. The statement is inheriting from instances of these templates. This trick of nesting the templates inside structs makes the statement code considerably simpler (otherwise `insert_t` would have to be template template arguments...).

In order to get started, I suggest you use something like where.h as a template.

The first thing you need is the `no_returning_t` type. It basically looks like this (omitting lots of boiler plate that I would love to get rid of but don't know how without macros):

```C++
struct no_returning_t
{
    template <typename Policies>
    struct _base_t // This is the base class for the statement.
    {
      template <typename Check, typename T>
      using _new_statement_t = new_statement_t<Check::value, Policies, no_returning_t, T>;

      template <typename... Expressions>
      auto returning(Expressions... expressions) const
          -> _new_statement_t<std::true_type, returning_t<void, Expressions...>>
      {
         return {static_cast<const derived_statement_t<Policies>&>(*this),
                returning_data_t<Database, Expressions...>{expressions...}};
      }
    };
};
```

The `_new_statement_t` is the type of the new statement. It replaces `no_returning_t` with `returning_t`.

`returning_data_t` is a struct to store the expressions.

Later on, you will want to add error checking, replacing the `true_type` and adding tag dispatch. As long as we do not have Concepts, `no_where_t` shows my preferred style of doing this. I explain this in my talk at CppCon 2015, starting around here https://youtu.be/2ISqFW9fRws?t=1901

`returning_t` represents the `returning` sub-clause in the new statement, once you called `returning()`. It has the same structure as `no_returning_t`. If you start with `where_t`, I would omit all `add` methods in the beginning and set the `_consistency_check` to `consistent_t` (Here you could add final checks before the statement is executed, allowing you to analyze the full statement).

In order to get started, I suggest using where_t, replace where with returning, and play with that for a while. Once you feel reasonably comfortable, look at select_column_list again. It will be much easier then.

The main difference is the _result_methods_t. It gives details of what the query will return.


Not exactly a perfect tutorial, I know, but I hope this helps to get going.

Let me know if you run into problems (e.g. it might make sense to factor some parts of the select_column_list.h file out into something else).

Best regards,

Roland

**Comment by cszawisza** [comment]
Hi!
Did you see my implementation of returning in insert statement? I've manage to make it work by reimplementing the insert from sqlpp.
You can see it in 
https://github.com/cszawisza/sqlpp11-connector-postgresql/blob/master/include/sqlpp11/postgresql/insert.h#L141-L147
and some example usage at 
https://github.com/cszawisza/eedb/blob/master/src/server/core/ProcessingUnits/CategoryPU.cpp#L79-L86
I did not create a pull request, because I'm not sure that this implementation is correct, but if you find this code useful, please don't hesitate and use it :)

**Comment by matthijs** [comment]
Hi,

Jee, I have checked your repository but I somehow missed that!
Thank you, I'll look at it.

I still need to learn a bit about this, but it gives me the chance to learn about C++ templates and the sqlpp11 library!

I started my implementation in the feature/returning branch and added a testcase for it too. 

Regards, Matthijs

**Comment by cszawisza** [comment]
Hi!
I've recently manage to add some code to this library, but I stuck on returning feature... 
In short, returning feature works on MockDb, but when I uncomment -> https://github.com/cszawisza/sqlpp11-connector-postgresql/blob/229a7eb54e6903764bf3414a972f12fc430976ff/tests/Returning.cpp#L14-L47 
compilation fails giving -> https://gist.github.com/cszawisza/9d4c46cf500b2ab2cfce
I can’t find any way to make it work, any suggestions?

**Comment by rbock** [comment]
Looking at the error message, I guess that this is the main problem:

> /usr/local/include/sqlpp11/result_row.h:155:5: note:   no known conversion for argument 1 from 
> 'const sqlpp::postgresql::dynamic_returning_column_list<void>::_names_t' to 
> 'const sqlpp::dynamic_select_column_list<void>::_names_t&'

If you look into those files, you'll see this:

```
  template <>
  struct dynamic_select_column_list<void>
  {
    struct _names_t
    {
      static constexpr size_t size()
      {
        return 0;
      }
    };
    _names_t _dynamic_expression_names;

    static constexpr bool empty()
    {
      return true;
    }
  };
```

And there is the same (but a different template name) in your new returning feature. 

This is a bit of a relic, I am afraid. There are several ways to solve this.

I just pushed an update to develop that includes <sqlpp11/no_name.h> and then 

```
  template <>
  struct dynamic_select_column_list<void>
  {
    using _names_t = no_name_t;
    _names_t _dynamic_expression_names;

    static constexpr bool empty()
    {
      return true;
    }
  };
```

You could do the same, but beware, I made a few breaking changes in develop (towards improved compile-time safety) and haven't documented the migration path yet.

You could also just use `dynamic_select_column_list` instead of `dynamic_returning_column_list` in your code. That should work just fine.

Best,

Roland

**Comment by cszawisza** [comment]
Thanks Roland, it works like a charm :)
 
Fixed in https://github.com/cszawisza/sqlpp11-connector-postgresql/commit/3543917d6a3999278801fd1c108e6ca6234b5b7d

I also add "update" with returning feature https://github.com/cszawisza/sqlpp11-connector-postgresql/commit/092a95862b3dbe918364e2effe52c34811c1474f

thanks for your help

**Comment by rbock** [comment]
Glad to help, and I am happy to see that you had no trouble adjusting to the changes in sqlpp11-develop :-)

**Comment by matthijs** [comment]
Ok, lets get a bit more active, hopefully I can continue the development.

I guess this ticket can be closed as there is now support for the RETURNING clause.

Thanks to everyone who have done pull requests / commits!

**Comment by cszawisza** [comment]
Last time I check there was a BUG in the returning clause, you could add there columns from different table then use in insert/update statement (but I can be wrong of course), need to be checked before close.

**Comment by matthijs** [comment]
Ok, thanks for the info. I will take a look.

**Comment by matthijs** [comment]
Yes, you are correct about this. I'm able to compile the following which should not happen. Let me see if I can fix that.

```c++
model::TabFoo foo;
model::TabBar bar;

auto sql = sqlpp::postgresql::insert_into(foo).set(foo.gamma = "bla").returning(foo.c_timepoint, bar.c_int);
```

**Comment by matthijs** [comment]
I've checked this right now and the above works perfect. I've added an extra static_assert on Columns. Empty columns are not possible.

```c++
auto sql = sqlpp::postgresql::insert_into(foo).set(foo.gamma = "bla").returning();

/home/matthijs/src/sqlpp11-connector-postgresql/include/sqlpp11/postgresql/returning.h:127:11: error:
      static_assert failed due to requirement 'sizeof...(Columns)' "at least one
      returnable expression (e.g. a column) is required in returning"
          static_assert(sizeof...(Columns),
```

```c++
auto sql = sqlpp::postgresql::insert_into(foo).set(foo.gamma = "bla").returning(bar.c_int);
MockDb dummydb;
const auto res = dummydb(sql);

/home/matthijs/src/sqlpp11-connector-postgresql/include/sqlpp11/postgresql/returning_column_list.h:165:5: error:
      static_assert failed due to requirement 'wrong_t<>::value' "at least one
      returning column requires a table which is otherwise not known in the
      statement"
    SQLPP_PORTABLE_STATIC_ASSERT(
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/sqlpp11/portable_static_assert.h:41:7: note: expanded from
      macro 'SQLPP_PORTABLE_STATIC_ASSERT'
      static_assert(wrong_t<T...>::value, message); \
      ^             ~~~~~~~~~~~~~~~~~~~~
```
